name: Metrics(lowlighter)
on:
  # Reference: https://github.com/lowlighter/metrics 
  # Schedule updates (every 2 days)
  schedule: [{cron: "0 0 */2 * *"}]
  # schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
